name: 📦 构建 0.2.7 魔改版本
run-name: 📦 ${{ github.actor }} @ 构建 0.2.7 魔改版本

on:
  push:
    branches: ["n"]
  pull_request:
    branches: ["n"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 设置时区
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "当前时间: $(date)"

      - name: Checkout 仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"
          cache: gradle

      - name: 设置 Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: 授权 gradlew
        run: chmod +x gradlew

      - name: 🛠️ 编译 APK
        run: ./gradlew assembleNormalRelease assembleCompatibleRelease -Pversion=${{ github.ref_name }}

      - name: 📦 查找 APK
        id: locate_apks
        run: |
          normal_apk=$(find app/build/outputs/apk/normal/release -name "*.apk" | head -n 1)
          compatible_apk=$(find app/build/outputs/apk/compatible/release -name "*.apk" | head -n 1)
          echo "normal_apk=$normal_apk" >> $GITHUB_OUTPUT
          echo "compatible_apk=$compatible_apk" >> $GITHUB_OUTPUT

      - name: 🔐 签名 APK
        id: sign_apks
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/apk
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: 📁 提取签名 APK 路径
        id: extract_apks
        run: |
          IFS=':' read -r -a files <<< "${{ steps.sign_apks.outputs.signedFiles }}"
          for file in "${files[@]}"; do
            if [[ "$file" == *Normal* ]]; then
              echo "signed_normal=$file" >> $GITHUB_OUTPUT
            elif [[ "$file" == *Compatible* ]]; then
              echo "signed_compatible=$file" >> $GITHUB_OUTPUT
            fi
          done

      - name: 📤 上传构建产物 (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: apk-signed
          path: |
            ${{ steps.extract_apks.outputs.signed_normal }}
            ${{ steps.extract_apks.outputs.signed_compatible }}

      - name: 📜 获取版本号
        id: extract_info
        run: |
          filename=$(basename "${{ steps.extract_apks.outputs.signed_normal }}")
          version=$(echo "$filename" | sed -E 's/.*-Normal-(.*)-signed\.apk/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: 📊 获取提交日志
        id: commit_details
        run: |
          # 获取提交日志，并去除特殊符号（如括号、尖括号、换行符等）
          MSG=$(git log -5 --pretty=format:"- %s by %an" --no-merges | sed 's/[^a-zA-Z0-9 \-_/\.]//g')
          
          # 输出处理后的消息
          echo "COMMITS=$MSG" >> $GITHUB_OUTPUT

      # 📨 发送 Telegram 消息（更美观）
      - name: 📢 发送构建消息到 Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            📦 *Sesame 0.2.7 魔改版本已构建完成！*
            
            🔖 版本号: `${{ steps.extract_info.outputs.version }}`
            🛠 分支: `${{ github.ref_name }}`
            👤 构建者: `${{ github.actor }}`

            📜 更新内容:
            ${{ steps.commit_details.outputs.COMMITS }}

            📥 下载说明:
            - 📱 *Normal*: 适用于 Android 8.0 及以上
            - 📲 *Compatible*: 适用于 Android 5.1 ~ 7.0

          format: markdown

      - name: 📤 发送 APK - Normal
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          document: ${{ steps.extract_apks.outputs.signed_normal }}

      - name: 📤 发送 APK - Compatible
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          document: ${{ steps.extract_apks.outputs.signed_compatible }}

      # 📦 发布到 GitHub Release
      - name: 📦 发布 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_info.outputs.version }}
          name: "📦 Sesame 0.2.7 魔改版 - v${{ steps.extract_info.outputs.version }}"
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            ${{ steps.extract_apks.outputs.signed_normal }}
            ${{ steps.extract_apks.outputs.signed_compatible }}
          body: |
            ## ✨ 更新内容
            ${{ steps.commit_details.outputs.COMMITS }}

            ## 📥 下载说明
            - 📱 **Normal**：适用于 Android 8.0+
            - 📲 **Compatible**：适用于 Android 5.1 ~ 7.0

            🚨 *墙内不再更新，倒卖必死全家*